version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: campaignmysql
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
